### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by NavineClient** [ProJakob/navine#5]
Hey Jakob, I just found my account info with this account and got back into it, just letting you know that I have some ideas for the client and will let you know in dms on DC. Hope you see this message.
P.S I'm at work so I'll be home around 2-3 pm EST.

**Comment by NavineClient** [comment]
Also, since you maybe remember who I am, could you send me any untested versions of the client so I could test then for ya. I'm bored when I'm home so it'll give me some to do. Make sure to give me the version they supposed to be on, the fabric loader version, and others too if ya do it. Let me know as soon as ya can.
- @NavineClient

**Comment by NavineClient** [comment]
> Hello NavineClient How can i get 1.20.1 version of this client?

I think its either one of the versions on this site or I might have one of the versions saved on my computer.

**Comment by ProJakob** [comment]
The client is discontinued.
